databases:
  - name: sira-db
    plan: free
    databaseName: sira
    user: sira_user

services:
  - type: web
    name: sira-api
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sira-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "120"
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: DEBUG
        value: "False"
      - key: APP_VERSION
        value: "2.0.0"
